// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.yoursway.autoupdater.core.protos;

public final class LocalRepositoryProtos {
  private LocalRepositoryProtos() {}
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor = buildDescriptor();
  private static
      com.google.protobuf.Descriptors.FileDescriptor
      buildDescriptor() {
    java.lang.String descriptorData =
      "\n\033LocalRepositoryProtos.proto\"9\n\016Request" +
      "Memento\022\013\n\003url\030\001 \002(\t\022\014\n\004size\030\002 \002(\003\022\014\n\004sh" +
      "a1\030\003 \002(\t\"c\n\024ComponentFileMemento\022\014\n\004hash" +
      "\030\001 \002(\t\022\014\n\004size\030\002 \002(\003\022\020\n\010modified\030\003 \002(\003\022\017" +
      "\n\007attribs\030\006 \002(\t\022\014\n\004path\030\004 \002(\t\"n\n\032Compone" +
      "ntDefinitionMemento\022\014\n\004name\030\003 \002(\t\022#\n\004fil" +
      "e\030\001 \003(\0132\025.ComponentFileMemento\022\035\n\004pack\030\002" +
      " \003(\0132\017.RequestMemento\"<\n\030ProductDefiniti" +
      "onMemento\022\014\n\004name\030\001 \002(\t\022\022\n\nupdateSite\030\002 " +
      "\001(\t\"\314\001\n\037ProductVersionDefinitionMemento\022" +
      "*\n\007product\030\001 \002(\0132\031.ProductDefinitionMeme" +
      "nto\022\014\n\004name\030\005 \002(\t\022\014\n\004type\030\006 \002(\t\022\035\n\004pack\030" +
      "\002 \003(\0132\017.RequestMemento\022.\n\tcomponent\030\003 \003(" +
      "\0132\033.ComponentDefinitionMemento\022\022\n\nexecut" +
      "able\030\004 \002(\t\"\362\001\n\032LocalProductVersionMement" +
      "o\0224\n\ndefinition\030\001 \002(\0132 .ProductVersionDe" +
      "finitionMemento\0220\n\005state\030\002 \002(\0162!.LocalPr" +
      "oductVersionMemento.State\"l\n\005State\022\010\n\004Id" +
      "le\020\000\022\016\n\nInstalling\020\001\022\026\n\022InstallingExtern" +
      "al\020\002\022\021\n\rInternalError\020\003\022\021\n\rInstallFailed" +
      "\020\004\022\013\n\007Crashed\020\005\"r\n\023LocalProductMemento\022-" +
      "\n\ndefinition\030\001 \002(\0132\031.ProductDefinitionMe" +
      "mento\022,\n\007version\030\002 \003(\0132\033.LocalProductVer" +
      "sionMemento\"?\n\026LocalRepositoryMemento\022%\n" +
      "\007product\030\001 \003(\0132\024.LocalProductMementoB&\n$" +
      "com.yoursway.autoupdater.core.protos";
    try {
      return com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
          });
    } catch (Exception e) {
      throw new RuntimeException(
        "Failed to parse protocol buffer descriptor for " +
        "\"LocalRepositoryProtos.proto\".", e);
    }
  }
  
  public static final class RequestMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use RequestMemento.newBuilder() to construct.
    private RequestMemento() {}
    
    private static final RequestMemento defaultInstance = new RequestMemento();
    public static RequestMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_RequestMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_RequestMemento_fieldAccessorTable;
    }
    
    // required string url = 1;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public boolean hasUrl() { return hasUrl; }
    public java.lang.String getUrl() { return url_; }
    
    // required int64 size = 2;
    private boolean hasSize;
    private long size_ = 0L;
    public boolean hasSize() { return hasSize; }
    public long getSize() { return size_; }
    
    // required string sha1 = 3;
    private boolean hasSha1;
    private java.lang.String sha1_ = "";
    public boolean hasSha1() { return hasSha1; }
    public java.lang.String getSha1() { return sha1_; }
    
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento();
      
      protected com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento buildPartial() {
        com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string url = 1;
      public boolean hasUrl() {
        return result.hasUrl();
      }
      public java.lang.String getUrl() {
        return result.getUrl();
      }
      public Builder setUrl(java.lang.String value) {
        result.hasUrl = true;
        result.url_ = value;
        return this;
      }
      public Builder clearUrl() {
        result.hasUrl = false;
        result.url_ = "";
        return this;
      }
      
      // required int64 size = 2;
      public boolean hasSize() {
        return result.hasSize();
      }
      public long getSize() {
        return result.getSize();
      }
      public Builder setSize(long value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = 0L;
        return this;
      }
      
      // required string sha1 = 3;
      public boolean hasSha1() {
        return result.hasSha1();
      }
      public java.lang.String getSha1() {
        return result.getSha1();
      }
      public Builder setSha1(java.lang.String value) {
        result.hasSha1 = true;
        result.sha1_ = value;
        return this;
      }
      public Builder clearSha1() {
        result.hasSha1 = false;
        result.sha1_ = "";
        return this;
      }
    }
  }
  
  public static final class ComponentFileMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ComponentFileMemento.newBuilder() to construct.
    private ComponentFileMemento() {}
    
    private static final ComponentFileMemento defaultInstance = new ComponentFileMemento();
    public static ComponentFileMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ComponentFileMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_ComponentFileMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_ComponentFileMemento_fieldAccessorTable;
    }
    
    // required string hash = 1;
    private boolean hasHash;
    private java.lang.String hash_ = "";
    public boolean hasHash() { return hasHash; }
    public java.lang.String getHash() { return hash_; }
    
    // required int64 size = 2;
    private boolean hasSize;
    private long size_ = 0L;
    public boolean hasSize() { return hasSize; }
    public long getSize() { return size_; }
    
    // required int64 modified = 3;
    private boolean hasModified;
    private long modified_ = 0L;
    public boolean hasModified() { return hasModified; }
    public long getModified() { return modified_; }
    
    // required string attribs = 6;
    private boolean hasAttribs;
    private java.lang.String attribs_ = "";
    public boolean hasAttribs() { return hasAttribs; }
    public java.lang.String getAttribs() { return attribs_; }
    
    // required string path = 4;
    private boolean hasPath;
    private java.lang.String path_ = "";
    public boolean hasPath() { return hasPath; }
    public java.lang.String getPath() { return path_; }
    
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento();
      
      protected com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento buildPartial() {
        com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string hash = 1;
      public boolean hasHash() {
        return result.hasHash();
      }
      public java.lang.String getHash() {
        return result.getHash();
      }
      public Builder setHash(java.lang.String value) {
        result.hasHash = true;
        result.hash_ = value;
        return this;
      }
      public Builder clearHash() {
        result.hasHash = false;
        result.hash_ = "";
        return this;
      }
      
      // required int64 size = 2;
      public boolean hasSize() {
        return result.hasSize();
      }
      public long getSize() {
        return result.getSize();
      }
      public Builder setSize(long value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = 0L;
        return this;
      }
      
      // required int64 modified = 3;
      public boolean hasModified() {
        return result.hasModified();
      }
      public long getModified() {
        return result.getModified();
      }
      public Builder setModified(long value) {
        result.hasModified = true;
        result.modified_ = value;
        return this;
      }
      public Builder clearModified() {
        result.hasModified = false;
        result.modified_ = 0L;
        return this;
      }
      
      // required string attribs = 6;
      public boolean hasAttribs() {
        return result.hasAttribs();
      }
      public java.lang.String getAttribs() {
        return result.getAttribs();
      }
      public Builder setAttribs(java.lang.String value) {
        result.hasAttribs = true;
        result.attribs_ = value;
        return this;
      }
      public Builder clearAttribs() {
        result.hasAttribs = false;
        result.attribs_ = "";
        return this;
      }
      
      // required string path = 4;
      public boolean hasPath() {
        return result.hasPath();
      }
      public java.lang.String getPath() {
        return result.getPath();
      }
      public Builder setPath(java.lang.String value) {
        result.hasPath = true;
        result.path_ = value;
        return this;
      }
      public Builder clearPath() {
        result.hasPath = false;
        result.path_ = "";
        return this;
      }
    }
  }
  
  public static final class ComponentDefinitionMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ComponentDefinitionMemento.newBuilder() to construct.
    private ComponentDefinitionMemento() {}
    
    private static final ComponentDefinitionMemento defaultInstance = new ComponentDefinitionMemento();
    public static ComponentDefinitionMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ComponentDefinitionMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_ComponentDefinitionMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_ComponentDefinitionMemento_fieldAccessorTable;
    }
    
    // required string name = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // repeated .ComponentFileMemento file = 1;
    private java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento> file_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento> getFileList() {
      return file_;
    }
    public int getFileCount() { return file_.size(); }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento getFile(int index) {
      return file_.get(index);
    }
    
    // repeated .RequestMemento pack = 2;
    private java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento> pack_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento> getPackList() {
      return pack_;
    }
    public int getPackCount() { return pack_.size(); }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento getPack(int index) {
      return pack_.get(index);
    }
    
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento();
      
      protected com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento buildPartial() {
        if (result.file_ != java.util.Collections.EMPTY_LIST) {
          result.file_ =
            java.util.Collections.unmodifiableList(result.file_);
        }
        if (result.pack_ != java.util.Collections.EMPTY_LIST) {
          result.pack_ =
            java.util.Collections.unmodifiableList(result.pack_);
        }
        com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // repeated .ComponentFileMemento file = 1;
      public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento> getFileList() {
        return java.util.Collections.unmodifiableList(result.file_);
      }
      public int getFileCount() {
        return result.getFileCount();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento getFile(int index) {
        return result.getFile(index);
      }
      public Builder setFile(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento value) {
        result.file_.set(index, value);
        return this;
      }
      public Builder setFile(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento.Builder builderForValue) {
        result.file_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFile(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento value) {
        if (result.file_.isEmpty()) {
          result.file_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento>();
        }
        result.file_.add(value);
        return this;
      }
      public Builder addFile(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento.Builder builderForValue) {
        if (result.file_.isEmpty()) {
          result.file_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento>();
        }
        result.file_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFile(
          java.lang.Iterable<? extends com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento> values) {
        if (result.file_.isEmpty()) {
          result.file_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento>();
        }
        super.addAll(values, result.file_);
        return this;
      }
      public Builder clearFile() {
        result.file_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .RequestMemento pack = 2;
      public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento> getPackList() {
        return java.util.Collections.unmodifiableList(result.pack_);
      }
      public int getPackCount() {
        return result.getPackCount();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento getPack(int index) {
        return result.getPack(index);
      }
      public Builder setPack(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento value) {
        result.pack_.set(index, value);
        return this;
      }
      public Builder setPack(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento.Builder builderForValue) {
        result.pack_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento value) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento>();
        }
        result.pack_.add(value);
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento.Builder builderForValue) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento>();
        }
        result.pack_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPack(
          java.lang.Iterable<? extends com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento> values) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento>();
        }
        super.addAll(values, result.pack_);
        return this;
      }
      public Builder clearPack() {
        result.pack_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  public static final class ProductDefinitionMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ProductDefinitionMemento.newBuilder() to construct.
    private ProductDefinitionMemento() {}
    
    private static final ProductDefinitionMemento defaultInstance = new ProductDefinitionMemento();
    public static ProductDefinitionMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProductDefinitionMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_ProductDefinitionMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_ProductDefinitionMemento_fieldAccessorTable;
    }
    
    // required string name = 1;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string updateSite = 2;
    private boolean hasUpdateSite;
    private java.lang.String updateSite_ = "";
    public boolean hasUpdateSite() { return hasUpdateSite; }
    public java.lang.String getUpdateSite() { return updateSite_; }
    
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento();
      
      protected com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento buildPartial() {
        com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string name = 1;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // optional string updateSite = 2;
      public boolean hasUpdateSite() {
        return result.hasUpdateSite();
      }
      public java.lang.String getUpdateSite() {
        return result.getUpdateSite();
      }
      public Builder setUpdateSite(java.lang.String value) {
        result.hasUpdateSite = true;
        result.updateSite_ = value;
        return this;
      }
      public Builder clearUpdateSite() {
        result.hasUpdateSite = false;
        result.updateSite_ = "";
        return this;
      }
    }
  }
  
  public static final class ProductVersionDefinitionMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ProductVersionDefinitionMemento.newBuilder() to construct.
    private ProductVersionDefinitionMemento() {}
    
    private static final ProductVersionDefinitionMemento defaultInstance = new ProductVersionDefinitionMemento();
    public static ProductVersionDefinitionMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProductVersionDefinitionMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_ProductVersionDefinitionMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_ProductVersionDefinitionMemento_fieldAccessorTable;
    }
    
    // required .ProductDefinitionMemento product = 1;
    private boolean hasProduct;
    private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento product_ = com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.getDefaultInstance();
    public boolean hasProduct() { return hasProduct; }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento getProduct() { return product_; }
    
    // required string name = 5;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // required string type = 6;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    // repeated .RequestMemento pack = 2;
    private java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento> pack_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento> getPackList() {
      return pack_;
    }
    public int getPackCount() { return pack_.size(); }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento getPack(int index) {
      return pack_.get(index);
    }
    
    // repeated .ComponentDefinitionMemento component = 3;
    private java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento> component_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento> getComponentList() {
      return component_;
    }
    public int getComponentCount() { return component_.size(); }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento getComponent(int index) {
      return component_.get(index);
    }
    
    // required string executable = 4;
    private boolean hasExecutable;
    private java.lang.String executable_ = "";
    public boolean hasExecutable() { return hasExecutable; }
    public java.lang.String getExecutable() { return executable_; }
    
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento();
      
      protected com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento buildPartial() {
        if (result.pack_ != java.util.Collections.EMPTY_LIST) {
          result.pack_ =
            java.util.Collections.unmodifiableList(result.pack_);
        }
        if (result.component_ != java.util.Collections.EMPTY_LIST) {
          result.component_ =
            java.util.Collections.unmodifiableList(result.component_);
        }
        com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .ProductDefinitionMemento product = 1;
      public boolean hasProduct() {
        return result.hasProduct();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento getProduct() {
        return result.getProduct();
      }
      public Builder setProduct(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento value) {
        result.hasProduct = true;
        result.product_ = value;
        return this;
      }
      public Builder setProduct(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.Builder builderForValue) {
        result.hasProduct = true;
        result.product_ = builderForValue.build();
        return this;
      }
      public Builder mergeProduct(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento value) {
        if (result.hasProduct() &&
            result.product_ != com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.getDefaultInstance()) {
          result.product_ =
            com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.newBuilder(result.product_).mergeFrom(value).buildPartial();
        } else {
          result.product_ = value;
        }
        result.hasProduct = true;
        return this;
      }
      public Builder clearProduct() {
        result.hasProduct = false;
        result.product_ = com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.getDefaultInstance();
        return this;
      }
      
      // required string name = 5;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = "";
        return this;
      }
      
      // required string type = 6;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = "";
        return this;
      }
      
      // repeated .RequestMemento pack = 2;
      public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento> getPackList() {
        return java.util.Collections.unmodifiableList(result.pack_);
      }
      public int getPackCount() {
        return result.getPackCount();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento getPack(int index) {
        return result.getPack(index);
      }
      public Builder setPack(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento value) {
        result.pack_.set(index, value);
        return this;
      }
      public Builder setPack(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento.Builder builderForValue) {
        result.pack_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento value) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento>();
        }
        result.pack_.add(value);
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento.Builder builderForValue) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento>();
        }
        result.pack_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPack(
          java.lang.Iterable<? extends com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento> values) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento>();
        }
        super.addAll(values, result.pack_);
        return this;
      }
      public Builder clearPack() {
        result.pack_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .ComponentDefinitionMemento component = 3;
      public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento> getComponentList() {
        return java.util.Collections.unmodifiableList(result.component_);
      }
      public int getComponentCount() {
        return result.getComponentCount();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento getComponent(int index) {
        return result.getComponent(index);
      }
      public Builder setComponent(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento value) {
        result.component_.set(index, value);
        return this;
      }
      public Builder setComponent(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento.Builder builderForValue) {
        result.component_.set(index, builderForValue.build());
        return this;
      }
      public Builder addComponent(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento value) {
        if (result.component_.isEmpty()) {
          result.component_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento>();
        }
        result.component_.add(value);
        return this;
      }
      public Builder addComponent(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento.Builder builderForValue) {
        if (result.component_.isEmpty()) {
          result.component_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento>();
        }
        result.component_.add(builderForValue.build());
        return this;
      }
      public Builder addAllComponent(
          java.lang.Iterable<? extends com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento> values) {
        if (result.component_.isEmpty()) {
          result.component_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento>();
        }
        super.addAll(values, result.component_);
        return this;
      }
      public Builder clearComponent() {
        result.component_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string executable = 4;
      public boolean hasExecutable() {
        return result.hasExecutable();
      }
      public java.lang.String getExecutable() {
        return result.getExecutable();
      }
      public Builder setExecutable(java.lang.String value) {
        result.hasExecutable = true;
        result.executable_ = value;
        return this;
      }
      public Builder clearExecutable() {
        result.hasExecutable = false;
        result.executable_ = "";
        return this;
      }
    }
  }
  
  public static final class LocalProductVersionMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use LocalProductVersionMemento.newBuilder() to construct.
    private LocalProductVersionMemento() {}
    
    private static final LocalProductVersionMemento defaultInstance = new LocalProductVersionMemento();
    public static LocalProductVersionMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public LocalProductVersionMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_LocalProductVersionMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_LocalProductVersionMemento_fieldAccessorTable;
    }
    
    public static enum State {
      Idle(0, 0),
      Installing(1, 1),
      InstallingExternal(2, 2),
      InternalError(3, 3),
      InstallFailed(4, 4),
      Crashed(5, 5),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static State valueOf(int value) {
        switch (value) {
          case 0: return Idle;
          case 1: return Installing;
          case 2: return InstallingExternal;
          case 3: return InternalError;
          case 4: return InstallFailed;
          case 5: return Crashed;
          default: return null;
        }
      }
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final State[] VALUES = {
        Idle, Installing, InstallingExternal, InternalError, InstallFailed, Crashed, 
      };
      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private State(int index, int value) {
        this.index = index;
        this.value = value;
      }
    }
    
    // required .ProductVersionDefinitionMemento definition = 1;
    private boolean hasDefinition;
    private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento definition_ = com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance();
    public boolean hasDefinition() { return hasDefinition; }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento getDefinition() { return definition_; }
    
    // required .LocalProductVersionMemento.State state = 2;
    private boolean hasState;
    private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.State state_ = com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.State.Idle;
    public boolean hasState() { return hasState; }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.State getState() { return state_; }
    
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento();
      
      protected com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento buildPartial() {
        com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .ProductVersionDefinitionMemento definition = 1;
      public boolean hasDefinition() {
        return result.hasDefinition();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento getDefinition() {
        return result.getDefinition();
      }
      public Builder setDefinition(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento value) {
        result.hasDefinition = true;
        result.definition_ = value;
        return this;
      }
      public Builder setDefinition(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.Builder builderForValue) {
        result.hasDefinition = true;
        result.definition_ = builderForValue.build();
        return this;
      }
      public Builder mergeDefinition(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento value) {
        if (result.hasDefinition() &&
            result.definition_ != com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance()) {
          result.definition_ =
            com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.newBuilder(result.definition_).mergeFrom(value).buildPartial();
        } else {
          result.definition_ = value;
        }
        result.hasDefinition = true;
        return this;
      }
      public Builder clearDefinition() {
        result.hasDefinition = false;
        result.definition_ = com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance();
        return this;
      }
      
      // required .LocalProductVersionMemento.State state = 2;
      public boolean hasState() {
        return result.hasState();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.State getState() {
        return result.getState();
      }
      public Builder setState(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.State value) {
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.State.Idle;
        return this;
      }
    }
  }
  
  public static final class LocalProductMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use LocalProductMemento.newBuilder() to construct.
    private LocalProductMemento() {}
    
    private static final LocalProductMemento defaultInstance = new LocalProductMemento();
    public static LocalProductMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public LocalProductMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_LocalProductMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_LocalProductMemento_fieldAccessorTable;
    }
    
    // required .ProductDefinitionMemento definition = 1;
    private boolean hasDefinition;
    private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento definition_ = com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.getDefaultInstance();
    public boolean hasDefinition() { return hasDefinition; }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento getDefinition() { return definition_; }
    
    // repeated .LocalProductVersionMemento version = 2;
    private java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento> version_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento> getVersionList() {
      return version_;
    }
    public int getVersionCount() { return version_.size(); }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento getVersion(int index) {
      return version_.get(index);
    }
    
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento();
      
      protected com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento buildPartial() {
        if (result.version_ != java.util.Collections.EMPTY_LIST) {
          result.version_ =
            java.util.Collections.unmodifiableList(result.version_);
        }
        com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .ProductDefinitionMemento definition = 1;
      public boolean hasDefinition() {
        return result.hasDefinition();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento getDefinition() {
        return result.getDefinition();
      }
      public Builder setDefinition(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento value) {
        result.hasDefinition = true;
        result.definition_ = value;
        return this;
      }
      public Builder setDefinition(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.Builder builderForValue) {
        result.hasDefinition = true;
        result.definition_ = builderForValue.build();
        return this;
      }
      public Builder mergeDefinition(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento value) {
        if (result.hasDefinition() &&
            result.definition_ != com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.getDefaultInstance()) {
          result.definition_ =
            com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.newBuilder(result.definition_).mergeFrom(value).buildPartial();
        } else {
          result.definition_ = value;
        }
        result.hasDefinition = true;
        return this;
      }
      public Builder clearDefinition() {
        result.hasDefinition = false;
        result.definition_ = com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.getDefaultInstance();
        return this;
      }
      
      // repeated .LocalProductVersionMemento version = 2;
      public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento> getVersionList() {
        return java.util.Collections.unmodifiableList(result.version_);
      }
      public int getVersionCount() {
        return result.getVersionCount();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento getVersion(int index) {
        return result.getVersion(index);
      }
      public Builder setVersion(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento value) {
        result.version_.set(index, value);
        return this;
      }
      public Builder setVersion(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.Builder builderForValue) {
        result.version_.set(index, builderForValue.build());
        return this;
      }
      public Builder addVersion(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento value) {
        if (result.version_.isEmpty()) {
          result.version_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento>();
        }
        result.version_.add(value);
        return this;
      }
      public Builder addVersion(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.Builder builderForValue) {
        if (result.version_.isEmpty()) {
          result.version_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento>();
        }
        result.version_.add(builderForValue.build());
        return this;
      }
      public Builder addAllVersion(
          java.lang.Iterable<? extends com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento> values) {
        if (result.version_.isEmpty()) {
          result.version_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento>();
        }
        super.addAll(values, result.version_);
        return this;
      }
      public Builder clearVersion() {
        result.version_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  public static final class LocalRepositoryMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use LocalRepositoryMemento.newBuilder() to construct.
    private LocalRepositoryMemento() {}
    
    private static final LocalRepositoryMemento defaultInstance = new LocalRepositoryMemento();
    public static LocalRepositoryMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public LocalRepositoryMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_LocalRepositoryMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.internal_static_LocalRepositoryMemento_fieldAccessorTable;
    }
    
    // repeated .LocalProductMemento product = 1;
    private java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento> product_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento> getProductList() {
      return product_;
    }
    public int getProductCount() { return product_.size(); }
    public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento getProduct(int index) {
      return product_.get(index);
    }
    
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento();
      
      protected com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento buildPartial() {
        if (result.product_ != java.util.Collections.EMPTY_LIST) {
          result.product_ =
            java.util.Collections.unmodifiableList(result.product_);
        }
        com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .LocalProductMemento product = 1;
      public java.util.List<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento> getProductList() {
        return java.util.Collections.unmodifiableList(result.product_);
      }
      public int getProductCount() {
        return result.getProductCount();
      }
      public com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento getProduct(int index) {
        return result.getProduct(index);
      }
      public Builder setProduct(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento value) {
        result.product_.set(index, value);
        return this;
      }
      public Builder setProduct(int index, com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento.Builder builderForValue) {
        result.product_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProduct(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento value) {
        if (result.product_.isEmpty()) {
          result.product_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento>();
        }
        result.product_.add(value);
        return this;
      }
      public Builder addProduct(com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento.Builder builderForValue) {
        if (result.product_.isEmpty()) {
          result.product_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento>();
        }
        result.product_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProduct(
          java.lang.Iterable<? extends com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento> values) {
        if (result.product_.isEmpty()) {
          result.product_ = new java.util.ArrayList<com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento>();
        }
        super.addAll(values, result.product_);
        return this;
      }
      public Builder clearProduct() {
        result.product_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMemento_descriptor =
      getDescriptor().getMessageTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_RequestMemento_descriptor,
          new java.lang.String[] { "Url", "Size", "Sha1", },
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento.class,
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.RequestMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComponentFileMemento_descriptor =
      getDescriptor().getMessageTypes().get(1);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ComponentFileMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ComponentFileMemento_descriptor,
          new java.lang.String[] { "Hash", "Size", "Modified", "Attribs", "Path", },
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento.class,
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentFileMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComponentDefinitionMemento_descriptor =
      getDescriptor().getMessageTypes().get(2);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ComponentDefinitionMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ComponentDefinitionMemento_descriptor,
          new java.lang.String[] { "Name", "File", "Pack", },
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento.class,
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ComponentDefinitionMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductDefinitionMemento_descriptor =
      getDescriptor().getMessageTypes().get(3);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductDefinitionMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ProductDefinitionMemento_descriptor,
          new java.lang.String[] { "Name", "UpdateSite", },
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.class,
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductDefinitionMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductVersionDefinitionMemento_descriptor =
      getDescriptor().getMessageTypes().get(4);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductVersionDefinitionMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ProductVersionDefinitionMemento_descriptor,
          new java.lang.String[] { "Product", "Name", "Type", "Pack", "Component", "Executable", },
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.class,
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalProductVersionMemento_descriptor =
      getDescriptor().getMessageTypes().get(5);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LocalProductVersionMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_LocalProductVersionMemento_descriptor,
          new java.lang.String[] { "Definition", "State", },
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.class,
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductVersionMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalProductMemento_descriptor =
      getDescriptor().getMessageTypes().get(6);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LocalProductMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_LocalProductMemento_descriptor,
          new java.lang.String[] { "Definition", "Version", },
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento.class,
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalProductMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalRepositoryMemento_descriptor =
      getDescriptor().getMessageTypes().get(7);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LocalRepositoryMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_LocalRepositoryMemento_descriptor,
          new java.lang.String[] { "Product", },
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento.class,
          com.yoursway.autoupdater.core.protos.LocalRepositoryProtos.LocalRepositoryMemento.Builder.class);
}
