// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.yoursway.autoupdater.protos;

public final class ExternalInstallerProtos {
  private ExternalInstallerProtos() {}
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor = buildDescriptor();
  private static
      com.google.protobuf.Descriptors.FileDescriptor
      buildDescriptor() {
    java.lang.String descriptorData =
      "\n\035ExternalInstallerProtos.proto\")\n\013PackM" +
      "emento\022\014\n\004hash\030\001 \002(\t\022\014\n\004path\030\002 \002(\t\"*\n\014Pa" +
      "cksMemento\022\032\n\004pack\030\001 \003(\0132\014.PackMemento\"\033" +
      "\n\013FileMemento\022\014\n\004path\030\001 \002(\tB!\n\037com.yours" +
      "way.autoupdater.protos";
    try {
      return com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
          });
    } catch (Exception e) {
      throw new RuntimeException(
        "Failed to parse protocol buffer descriptor for " +
        "\"ExternalInstallerProtos.proto\".", e);
    }
  }
  
  public static final class PackMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use PackMemento.newBuilder() to construct.
    private PackMemento() {}
    
    private static final PackMemento defaultInstance = new PackMemento();
    public static PackMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public PackMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.ExternalInstallerProtos.internal_static_PackMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.ExternalInstallerProtos.internal_static_PackMemento_fieldAccessorTable;
    }
    
    // required string hash = 1;
    private boolean hasHash;
    private java.lang.String hash_ = "";
    public boolean hasHash() { return hasHash; }
    public java.lang.String getHash() { return hash_; }
    
    // required string path = 2;
    private boolean hasPath;
    private java.lang.String path_ = "";
    public boolean hasPath() { return hasPath; }
    public java.lang.String getPath() { return path_; }
    
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento result = new com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento();
      
      protected com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento buildPartial() {
        com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string hash = 1;
      public boolean hasHash() {
        return result.hasHash();
      }
      public java.lang.String getHash() {
        return result.getHash();
      }
      public Builder setHash(java.lang.String value) {
        result.hasHash = true;
        result.hash_ = value;
        return this;
      }
      public Builder clearHash() {
        result.hasHash = false;
        result.hash_ = "";
        return this;
      }
      
      // required string path = 2;
      public boolean hasPath() {
        return result.hasPath();
      }
      public java.lang.String getPath() {
        return result.getPath();
      }
      public Builder setPath(java.lang.String value) {
        result.hasPath = true;
        result.path_ = value;
        return this;
      }
      public Builder clearPath() {
        result.hasPath = false;
        result.path_ = "";
        return this;
      }
    }
  }
  
  public static final class PacksMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use PacksMemento.newBuilder() to construct.
    private PacksMemento() {}
    
    private static final PacksMemento defaultInstance = new PacksMemento();
    public static PacksMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public PacksMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.ExternalInstallerProtos.internal_static_PacksMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.ExternalInstallerProtos.internal_static_PacksMemento_fieldAccessorTable;
    }
    
    // repeated .PackMemento pack = 1;
    private java.util.List<com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento> pack_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento> getPackList() {
      return pack_;
    }
    public int getPackCount() { return pack_.size(); }
    public com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento getPack(int index) {
      return pack_.get(index);
    }
    
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento result = new com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento();
      
      protected com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento buildPartial() {
        if (result.pack_ != java.util.Collections.EMPTY_LIST) {
          result.pack_ =
            java.util.Collections.unmodifiableList(result.pack_);
        }
        com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .PackMemento pack = 1;
      public java.util.List<com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento> getPackList() {
        return java.util.Collections.unmodifiableList(result.pack_);
      }
      public int getPackCount() {
        return result.getPackCount();
      }
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento getPack(int index) {
        return result.getPack(index);
      }
      public Builder setPack(int index, com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento value) {
        result.pack_.set(index, value);
        return this;
      }
      public Builder setPack(int index, com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento.Builder builderForValue) {
        result.pack_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento value) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento>();
        }
        result.pack_.add(value);
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento.Builder builderForValue) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento>();
        }
        result.pack_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPack(
          java.lang.Iterable<? extends com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento> values) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento>();
        }
        super.addAll(values, result.pack_);
        return this;
      }
      public Builder clearPack() {
        result.pack_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  public static final class FileMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use FileMemento.newBuilder() to construct.
    private FileMemento() {}
    
    private static final FileMemento defaultInstance = new FileMemento();
    public static FileMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public FileMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.ExternalInstallerProtos.internal_static_FileMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.ExternalInstallerProtos.internal_static_FileMemento_fieldAccessorTable;
    }
    
    // required string path = 1;
    private boolean hasPath;
    private java.lang.String path_ = "";
    public boolean hasPath() { return hasPath; }
    public java.lang.String getPath() { return path_; }
    
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento result = new com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento();
      
      protected com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento buildPartial() {
        com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string path = 1;
      public boolean hasPath() {
        return result.hasPath();
      }
      public java.lang.String getPath() {
        return result.getPath();
      }
      public Builder setPath(java.lang.String value) {
        result.hasPath = true;
        result.path_ = value;
        return this;
      }
      public Builder clearPath() {
        result.hasPath = false;
        result.path_ = "";
        return this;
      }
    }
  }
  
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PackMemento_descriptor =
      getDescriptor().getMessageTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PackMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_PackMemento_descriptor,
          new java.lang.String[] { "Hash", "Path", },
          com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento.class,
          com.yoursway.autoupdater.protos.ExternalInstallerProtos.PackMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PacksMemento_descriptor =
      getDescriptor().getMessageTypes().get(1);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PacksMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_PacksMemento_descriptor,
          new java.lang.String[] { "Pack", },
          com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento.class,
          com.yoursway.autoupdater.protos.ExternalInstallerProtos.PacksMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FileMemento_descriptor =
      getDescriptor().getMessageTypes().get(2);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_FileMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_FileMemento_descriptor,
          new java.lang.String[] { "Path", },
          com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento.class,
          com.yoursway.autoupdater.protos.ExternalInstallerProtos.FileMemento.Builder.class);
}
