// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.yoursway.autoupdater.protos;

public final class InstallationProtos {
  private InstallationProtos() {}
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor = buildDescriptor();
  private static
      com.google.protobuf.Descriptors.FileDescriptor
      buildDescriptor() {
    java.lang.String descriptorData =
      "\n\030InstallationProtos.proto\032\033LocalReposit" +
      "oryProtos.proto\")\n\013PackMemento\022\014\n\004hash\030\001" +
      " \002(\t\022\014\n\004path\030\002 \002(\t\"\273\001\n\023InstallationMemen" +
      "to\0221\n\007current\030\001 \002(\0132 .ProductVersionDefi" +
      "nitionMemento\0221\n\007version\030\002 \002(\0132 .Product" +
      "VersionDefinitionMemento\022\032\n\004pack\030\003 \003(\0132\014" +
      ".PackMemento\022\016\n\006target\030\004 \002(\t\022\022\n\nexecutab" +
      "le\030\005 \002(\tB!\n\037com.yoursway.autoupdater.pro" +
      "tos";
    try {
      return com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
            com.yoursway.autoupdater.protos.LocalRepositoryProtos.getDescriptor(),
          });
    } catch (Exception e) {
      throw new RuntimeException(
        "Failed to parse protocol buffer descriptor for " +
        "\"InstallationProtos.proto\".", e);
    }
  }
  
  public static final class PackMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use PackMemento.newBuilder() to construct.
    private PackMemento() {}
    
    private static final PackMemento defaultInstance = new PackMemento();
    public static PackMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public PackMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.InstallationProtos.internal_static_PackMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.InstallationProtos.internal_static_PackMemento_fieldAccessorTable;
    }
    
    // required string hash = 1;
    private boolean hasHash;
    private java.lang.String hash_ = "";
    public boolean hasHash() { return hasHash; }
    public java.lang.String getHash() { return hash_; }
    
    // required string path = 2;
    private boolean hasPath;
    private java.lang.String path_ = "";
    public boolean hasPath() { return hasPath; }
    public java.lang.String getPath() { return path_; }
    
    public static com.yoursway.autoupdater.protos.InstallationProtos.PackMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.PackMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.PackMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.PackMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.PackMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.PackMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.PackMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.PackMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.InstallationProtos.PackMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.InstallationProtos.PackMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.InstallationProtos.PackMemento result = new com.yoursway.autoupdater.protos.InstallationProtos.PackMemento();
      
      protected com.yoursway.autoupdater.protos.InstallationProtos.PackMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.InstallationProtos.PackMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.InstallationProtos.PackMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.InstallationProtos.PackMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.InstallationProtos.PackMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.InstallationProtos.PackMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.InstallationProtos.PackMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.InstallationProtos.PackMemento buildPartial() {
        com.yoursway.autoupdater.protos.InstallationProtos.PackMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string hash = 1;
      public boolean hasHash() {
        return result.hasHash();
      }
      public java.lang.String getHash() {
        return result.getHash();
      }
      public Builder setHash(java.lang.String value) {
        result.hasHash = true;
        result.hash_ = value;
        return this;
      }
      public Builder clearHash() {
        result.hasHash = false;
        result.hash_ = "";
        return this;
      }
      
      // required string path = 2;
      public boolean hasPath() {
        return result.hasPath();
      }
      public java.lang.String getPath() {
        return result.getPath();
      }
      public Builder setPath(java.lang.String value) {
        result.hasPath = true;
        result.path_ = value;
        return this;
      }
      public Builder clearPath() {
        result.hasPath = false;
        result.path_ = "";
        return this;
      }
    }
  }
  
  public static final class InstallationMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use InstallationMemento.newBuilder() to construct.
    private InstallationMemento() {}
    
    private static final InstallationMemento defaultInstance = new InstallationMemento();
    public static InstallationMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public InstallationMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.InstallationProtos.internal_static_InstallationMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.InstallationProtos.internal_static_InstallationMemento_fieldAccessorTable;
    }
    
    // required .ProductVersionDefinitionMemento current = 1;
    private boolean hasCurrent;
    private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento current_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance();
    public boolean hasCurrent() { return hasCurrent; }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento getCurrent() { return current_; }
    
    // required .ProductVersionDefinitionMemento version = 2;
    private boolean hasVersion;
    private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento version_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance();
    public boolean hasVersion() { return hasVersion; }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento getVersion() { return version_; }
    
    // repeated .PackMemento pack = 3;
    private java.util.List<com.yoursway.autoupdater.protos.InstallationProtos.PackMemento> pack_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.protos.InstallationProtos.PackMemento> getPackList() {
      return pack_;
    }
    public int getPackCount() { return pack_.size(); }
    public com.yoursway.autoupdater.protos.InstallationProtos.PackMemento getPack(int index) {
      return pack_.get(index);
    }
    
    // required string target = 4;
    private boolean hasTarget;
    private java.lang.String target_ = "";
    public boolean hasTarget() { return hasTarget; }
    public java.lang.String getTarget() { return target_; }
    
    // required string executable = 5;
    private boolean hasExecutable;
    private java.lang.String executable_ = "";
    public boolean hasExecutable() { return hasExecutable; }
    public java.lang.String getExecutable() { return executable_; }
    
    public static com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento result = new com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento();
      
      protected com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento buildPartial() {
        if (result.pack_ != java.util.Collections.EMPTY_LIST) {
          result.pack_ =
            java.util.Collections.unmodifiableList(result.pack_);
        }
        com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .ProductVersionDefinitionMemento current = 1;
      public boolean hasCurrent() {
        return result.hasCurrent();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento getCurrent() {
        return result.getCurrent();
      }
      public Builder setCurrent(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento value) {
        result.hasCurrent = true;
        result.current_ = value;
        return this;
      }
      public Builder setCurrent(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.Builder builderForValue) {
        result.hasCurrent = true;
        result.current_ = builderForValue.build();
        return this;
      }
      public Builder mergeCurrent(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento value) {
        if (result.hasCurrent() &&
            result.current_ != com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance()) {
          result.current_ =
            com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.newBuilder(result.current_).mergeFrom(value).buildPartial();
        } else {
          result.current_ = value;
        }
        result.hasCurrent = true;
        return this;
      }
      public Builder clearCurrent() {
        result.hasCurrent = false;
        result.current_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance();
        return this;
      }
      
      // required .ProductVersionDefinitionMemento version = 2;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento value) {
        result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder setVersion(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.Builder builderForValue) {
        result.hasVersion = true;
        result.version_ = builderForValue.build();
        return this;
      }
      public Builder mergeVersion(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento value) {
        if (result.hasVersion() &&
            result.version_ != com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance()) {
          result.version_ =
            com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.newBuilder(result.version_).mergeFrom(value).buildPartial();
        } else {
          result.version_ = value;
        }
        result.hasVersion = true;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionDefinitionMemento.getDefaultInstance();
        return this;
      }
      
      // repeated .PackMemento pack = 3;
      public java.util.List<com.yoursway.autoupdater.protos.InstallationProtos.PackMemento> getPackList() {
        return java.util.Collections.unmodifiableList(result.pack_);
      }
      public int getPackCount() {
        return result.getPackCount();
      }
      public com.yoursway.autoupdater.protos.InstallationProtos.PackMemento getPack(int index) {
        return result.getPack(index);
      }
      public Builder setPack(int index, com.yoursway.autoupdater.protos.InstallationProtos.PackMemento value) {
        result.pack_.set(index, value);
        return this;
      }
      public Builder setPack(int index, com.yoursway.autoupdater.protos.InstallationProtos.PackMemento.Builder builderForValue) {
        result.pack_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.protos.InstallationProtos.PackMemento value) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.InstallationProtos.PackMemento>();
        }
        result.pack_.add(value);
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.protos.InstallationProtos.PackMemento.Builder builderForValue) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.InstallationProtos.PackMemento>();
        }
        result.pack_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPack(
          java.lang.Iterable<? extends com.yoursway.autoupdater.protos.InstallationProtos.PackMemento> values) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.InstallationProtos.PackMemento>();
        }
        super.addAll(values, result.pack_);
        return this;
      }
      public Builder clearPack() {
        result.pack_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string target = 4;
      public boolean hasTarget() {
        return result.hasTarget();
      }
      public java.lang.String getTarget() {
        return result.getTarget();
      }
      public Builder setTarget(java.lang.String value) {
        result.hasTarget = true;
        result.target_ = value;
        return this;
      }
      public Builder clearTarget() {
        result.hasTarget = false;
        result.target_ = "";
        return this;
      }
      
      // required string executable = 5;
      public boolean hasExecutable() {
        return result.hasExecutable();
      }
      public java.lang.String getExecutable() {
        return result.getExecutable();
      }
      public Builder setExecutable(java.lang.String value) {
        result.hasExecutable = true;
        result.executable_ = value;
        return this;
      }
      public Builder clearExecutable() {
        result.hasExecutable = false;
        result.executable_ = "";
        return this;
      }
    }
  }
  
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PackMemento_descriptor =
      getDescriptor().getMessageTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_PackMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_PackMemento_descriptor,
          new java.lang.String[] { "Hash", "Path", },
          com.yoursway.autoupdater.protos.InstallationProtos.PackMemento.class,
          com.yoursway.autoupdater.protos.InstallationProtos.PackMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_InstallationMemento_descriptor =
      getDescriptor().getMessageTypes().get(1);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_InstallationMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_InstallationMemento_descriptor,
          new java.lang.String[] { "Current", "Version", "Pack", "Target", "Executable", },
          com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento.class,
          com.yoursway.autoupdater.protos.InstallationProtos.InstallationMemento.Builder.class);
}
