// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.yoursway.autoupdater.protos;

public final class LocalRepositoryProtos {
  private LocalRepositoryProtos() {}
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor = buildDescriptor();
  private static
      com.google.protobuf.Descriptors.FileDescriptor
      buildDescriptor() {
    java.lang.String descriptorData =
      "\n\033LocalRepositoryProtos.proto\"9\n\016Request" +
      "Memento\022\013\n\003url\030\001 \002(\t\022\014\n\004size\030\002 \002(\003\022\014\n\004sh" +
      "a1\030\003 \002(\t\"R\n\024ComponentFileMemento\022\014\n\004hash" +
      "\030\001 \002(\t\022\014\n\004size\030\002 \002(\003\022\020\n\010modified\030\003 \002(\003\022\014" +
      "\n\004path\030\004 \002(\t\"V\n\020ComponentMemento\022#\n\004file" +
      "\030\001 \003(\0132\025.ComponentFileMemento\022\035\n\004pack\030\002 " +
      "\003(\0132\017.RequestMemento\"\020\n\016ProductMemento\"\222" +
      "\001\n\025ProductVersionMemento\022 \n\007product\030\001 \002(" +
      "\0132\017.ProductMemento\022\035\n\004pack\030\002 \003(\0132\017.Reque" +
      "stMemento\022$\n\tcomponent\030\003 \003(\0132\021.Component" +
      "Memento\022\022\n\nexecutable\030\004 \002(\t\"\300\001\n\032ProductV" +
      "ersionStateMemento\022\'\n\007version\030\001 \002(\0132\026.Pr" +
      "oductVersionMemento\0220\n\005state\030\002 \002(\0162!.Pro" +
      "ductVersionStateMemento.State\"G\n\005State\022\007" +
      "\n\003New\020\000\022\017\n\013Downloading\020\001\022\016\n\nInstalling\020\002" +
      "\022\013\n\007Current\020\003\022\007\n\003Old\020\004\"e\n\023ProductStateMe" +
      "mento\022 \n\007product\030\001 \002(\0132\017.ProductMemento\022" +
      ",\n\007version\030\002 \003(\0132\033.ProductVersionStateMe" +
      "mento\"?\n\026LocalRepositoryMemento\022%\n\007produ" +
      "ct\030\001 \003(\0132\024.ProductStateMementoB!\n\037com.yo" +
      "ursway.autoupdater.protos";
    try {
      return com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
          new com.google.protobuf.Descriptors.FileDescriptor[] {
          });
    } catch (Exception e) {
      throw new RuntimeException(
        "Failed to parse protocol buffer descriptor for " +
        "\"LocalRepositoryProtos.proto\".", e);
    }
  }
  
  public static final class RequestMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use RequestMemento.newBuilder() to construct.
    private RequestMemento() {}
    
    private static final RequestMemento defaultInstance = new RequestMemento();
    public static RequestMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public RequestMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_RequestMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_RequestMemento_fieldAccessorTable;
    }
    
    // required string url = 1;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public boolean hasUrl() { return hasUrl; }
    public java.lang.String getUrl() { return url_; }
    
    // required int64 size = 2;
    private boolean hasSize;
    private long size_ = 0L;
    public boolean hasSize() { return hasSize; }
    public long getSize() { return size_; }
    
    // required string sha1 = 3;
    private boolean hasSha1;
    private java.lang.String sha1_ = "";
    public boolean hasSha1() { return hasSha1; }
    public java.lang.String getSha1() { return sha1_; }
    
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento();
      
      protected com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento buildPartial() {
        com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string url = 1;
      public boolean hasUrl() {
        return result.hasUrl();
      }
      public java.lang.String getUrl() {
        return result.getUrl();
      }
      public Builder setUrl(java.lang.String value) {
        result.hasUrl = true;
        result.url_ = value;
        return this;
      }
      public Builder clearUrl() {
        result.hasUrl = false;
        result.url_ = "";
        return this;
      }
      
      // required int64 size = 2;
      public boolean hasSize() {
        return result.hasSize();
      }
      public long getSize() {
        return result.getSize();
      }
      public Builder setSize(long value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = 0L;
        return this;
      }
      
      // required string sha1 = 3;
      public boolean hasSha1() {
        return result.hasSha1();
      }
      public java.lang.String getSha1() {
        return result.getSha1();
      }
      public Builder setSha1(java.lang.String value) {
        result.hasSha1 = true;
        result.sha1_ = value;
        return this;
      }
      public Builder clearSha1() {
        result.hasSha1 = false;
        result.sha1_ = "";
        return this;
      }
    }
  }
  
  public static final class ComponentFileMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ComponentFileMemento.newBuilder() to construct.
    private ComponentFileMemento() {}
    
    private static final ComponentFileMemento defaultInstance = new ComponentFileMemento();
    public static ComponentFileMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ComponentFileMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ComponentFileMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ComponentFileMemento_fieldAccessorTable;
    }
    
    // required string hash = 1;
    private boolean hasHash;
    private java.lang.String hash_ = "";
    public boolean hasHash() { return hasHash; }
    public java.lang.String getHash() { return hash_; }
    
    // required int64 size = 2;
    private boolean hasSize;
    private long size_ = 0L;
    public boolean hasSize() { return hasSize; }
    public long getSize() { return size_; }
    
    // required int64 modified = 3;
    private boolean hasModified;
    private long modified_ = 0L;
    public boolean hasModified() { return hasModified; }
    public long getModified() { return modified_; }
    
    // required string path = 4;
    private boolean hasPath;
    private java.lang.String path_ = "";
    public boolean hasPath() { return hasPath; }
    public java.lang.String getPath() { return path_; }
    
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento();
      
      protected com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento buildPartial() {
        com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required string hash = 1;
      public boolean hasHash() {
        return result.hasHash();
      }
      public java.lang.String getHash() {
        return result.getHash();
      }
      public Builder setHash(java.lang.String value) {
        result.hasHash = true;
        result.hash_ = value;
        return this;
      }
      public Builder clearHash() {
        result.hasHash = false;
        result.hash_ = "";
        return this;
      }
      
      // required int64 size = 2;
      public boolean hasSize() {
        return result.hasSize();
      }
      public long getSize() {
        return result.getSize();
      }
      public Builder setSize(long value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = 0L;
        return this;
      }
      
      // required int64 modified = 3;
      public boolean hasModified() {
        return result.hasModified();
      }
      public long getModified() {
        return result.getModified();
      }
      public Builder setModified(long value) {
        result.hasModified = true;
        result.modified_ = value;
        return this;
      }
      public Builder clearModified() {
        result.hasModified = false;
        result.modified_ = 0L;
        return this;
      }
      
      // required string path = 4;
      public boolean hasPath() {
        return result.hasPath();
      }
      public java.lang.String getPath() {
        return result.getPath();
      }
      public Builder setPath(java.lang.String value) {
        result.hasPath = true;
        result.path_ = value;
        return this;
      }
      public Builder clearPath() {
        result.hasPath = false;
        result.path_ = "";
        return this;
      }
    }
  }
  
  public static final class ComponentMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ComponentMemento.newBuilder() to construct.
    private ComponentMemento() {}
    
    private static final ComponentMemento defaultInstance = new ComponentMemento();
    public static ComponentMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ComponentMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ComponentMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ComponentMemento_fieldAccessorTable;
    }
    
    // repeated .ComponentFileMemento file = 1;
    private java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento> file_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento> getFileList() {
      return file_;
    }
    public int getFileCount() { return file_.size(); }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento getFile(int index) {
      return file_.get(index);
    }
    
    // repeated .RequestMemento pack = 2;
    private java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento> pack_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento> getPackList() {
      return pack_;
    }
    public int getPackCount() { return pack_.size(); }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento getPack(int index) {
      return pack_.get(index);
    }
    
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento();
      
      protected com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento buildPartial() {
        if (result.file_ != java.util.Collections.EMPTY_LIST) {
          result.file_ =
            java.util.Collections.unmodifiableList(result.file_);
        }
        if (result.pack_ != java.util.Collections.EMPTY_LIST) {
          result.pack_ =
            java.util.Collections.unmodifiableList(result.pack_);
        }
        com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .ComponentFileMemento file = 1;
      public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento> getFileList() {
        return java.util.Collections.unmodifiableList(result.file_);
      }
      public int getFileCount() {
        return result.getFileCount();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento getFile(int index) {
        return result.getFile(index);
      }
      public Builder setFile(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento value) {
        result.file_.set(index, value);
        return this;
      }
      public Builder setFile(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento.Builder builderForValue) {
        result.file_.set(index, builderForValue.build());
        return this;
      }
      public Builder addFile(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento value) {
        if (result.file_.isEmpty()) {
          result.file_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento>();
        }
        result.file_.add(value);
        return this;
      }
      public Builder addFile(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento.Builder builderForValue) {
        if (result.file_.isEmpty()) {
          result.file_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento>();
        }
        result.file_.add(builderForValue.build());
        return this;
      }
      public Builder addAllFile(
          java.lang.Iterable<? extends com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento> values) {
        if (result.file_.isEmpty()) {
          result.file_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento>();
        }
        super.addAll(values, result.file_);
        return this;
      }
      public Builder clearFile() {
        result.file_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .RequestMemento pack = 2;
      public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento> getPackList() {
        return java.util.Collections.unmodifiableList(result.pack_);
      }
      public int getPackCount() {
        return result.getPackCount();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento getPack(int index) {
        return result.getPack(index);
      }
      public Builder setPack(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento value) {
        result.pack_.set(index, value);
        return this;
      }
      public Builder setPack(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento.Builder builderForValue) {
        result.pack_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento value) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento>();
        }
        result.pack_.add(value);
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento.Builder builderForValue) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento>();
        }
        result.pack_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPack(
          java.lang.Iterable<? extends com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento> values) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento>();
        }
        super.addAll(values, result.pack_);
        return this;
      }
      public Builder clearPack() {
        result.pack_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  public static final class ProductMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ProductMemento.newBuilder() to construct.
    private ProductMemento() {}
    
    private static final ProductMemento defaultInstance = new ProductMemento();
    public static ProductMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProductMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ProductMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ProductMemento_fieldAccessorTable;
    }
    
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento();
      
      protected com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento buildPartial() {
        com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
    }
  }
  
  public static final class ProductVersionMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ProductVersionMemento.newBuilder() to construct.
    private ProductVersionMemento() {}
    
    private static final ProductVersionMemento defaultInstance = new ProductVersionMemento();
    public static ProductVersionMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProductVersionMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ProductVersionMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ProductVersionMemento_fieldAccessorTable;
    }
    
    // required .ProductMemento product = 1;
    private boolean hasProduct;
    private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento product_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.getDefaultInstance();
    public boolean hasProduct() { return hasProduct; }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento getProduct() { return product_; }
    
    // repeated .RequestMemento pack = 2;
    private java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento> pack_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento> getPackList() {
      return pack_;
    }
    public int getPackCount() { return pack_.size(); }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento getPack(int index) {
      return pack_.get(index);
    }
    
    // repeated .ComponentMemento component = 3;
    private java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento> component_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento> getComponentList() {
      return component_;
    }
    public int getComponentCount() { return component_.size(); }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento getComponent(int index) {
      return component_.get(index);
    }
    
    // required string executable = 4;
    private boolean hasExecutable;
    private java.lang.String executable_ = "";
    public boolean hasExecutable() { return hasExecutable; }
    public java.lang.String getExecutable() { return executable_; }
    
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento();
      
      protected com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento buildPartial() {
        if (result.pack_ != java.util.Collections.EMPTY_LIST) {
          result.pack_ =
            java.util.Collections.unmodifiableList(result.pack_);
        }
        if (result.component_ != java.util.Collections.EMPTY_LIST) {
          result.component_ =
            java.util.Collections.unmodifiableList(result.component_);
        }
        com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .ProductMemento product = 1;
      public boolean hasProduct() {
        return result.hasProduct();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento getProduct() {
        return result.getProduct();
      }
      public Builder setProduct(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento value) {
        result.hasProduct = true;
        result.product_ = value;
        return this;
      }
      public Builder setProduct(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.Builder builderForValue) {
        result.hasProduct = true;
        result.product_ = builderForValue.build();
        return this;
      }
      public Builder mergeProduct(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento value) {
        if (result.hasProduct() &&
            result.product_ != com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.getDefaultInstance()) {
          result.product_ =
            com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.newBuilder(result.product_).mergeFrom(value).buildPartial();
        } else {
          result.product_ = value;
        }
        result.hasProduct = true;
        return this;
      }
      public Builder clearProduct() {
        result.hasProduct = false;
        result.product_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.getDefaultInstance();
        return this;
      }
      
      // repeated .RequestMemento pack = 2;
      public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento> getPackList() {
        return java.util.Collections.unmodifiableList(result.pack_);
      }
      public int getPackCount() {
        return result.getPackCount();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento getPack(int index) {
        return result.getPack(index);
      }
      public Builder setPack(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento value) {
        result.pack_.set(index, value);
        return this;
      }
      public Builder setPack(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento.Builder builderForValue) {
        result.pack_.set(index, builderForValue.build());
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento value) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento>();
        }
        result.pack_.add(value);
        return this;
      }
      public Builder addPack(com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento.Builder builderForValue) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento>();
        }
        result.pack_.add(builderForValue.build());
        return this;
      }
      public Builder addAllPack(
          java.lang.Iterable<? extends com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento> values) {
        if (result.pack_.isEmpty()) {
          result.pack_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento>();
        }
        super.addAll(values, result.pack_);
        return this;
      }
      public Builder clearPack() {
        result.pack_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated .ComponentMemento component = 3;
      public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento> getComponentList() {
        return java.util.Collections.unmodifiableList(result.component_);
      }
      public int getComponentCount() {
        return result.getComponentCount();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento getComponent(int index) {
        return result.getComponent(index);
      }
      public Builder setComponent(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento value) {
        result.component_.set(index, value);
        return this;
      }
      public Builder setComponent(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento.Builder builderForValue) {
        result.component_.set(index, builderForValue.build());
        return this;
      }
      public Builder addComponent(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento value) {
        if (result.component_.isEmpty()) {
          result.component_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento>();
        }
        result.component_.add(value);
        return this;
      }
      public Builder addComponent(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento.Builder builderForValue) {
        if (result.component_.isEmpty()) {
          result.component_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento>();
        }
        result.component_.add(builderForValue.build());
        return this;
      }
      public Builder addAllComponent(
          java.lang.Iterable<? extends com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento> values) {
        if (result.component_.isEmpty()) {
          result.component_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento>();
        }
        super.addAll(values, result.component_);
        return this;
      }
      public Builder clearComponent() {
        result.component_ = java.util.Collections.emptyList();
        return this;
      }
      
      // required string executable = 4;
      public boolean hasExecutable() {
        return result.hasExecutable();
      }
      public java.lang.String getExecutable() {
        return result.getExecutable();
      }
      public Builder setExecutable(java.lang.String value) {
        result.hasExecutable = true;
        result.executable_ = value;
        return this;
      }
      public Builder clearExecutable() {
        result.hasExecutable = false;
        result.executable_ = "";
        return this;
      }
    }
  }
  
  public static final class ProductVersionStateMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ProductVersionStateMemento.newBuilder() to construct.
    private ProductVersionStateMemento() {}
    
    private static final ProductVersionStateMemento defaultInstance = new ProductVersionStateMemento();
    public static ProductVersionStateMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProductVersionStateMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ProductVersionStateMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ProductVersionStateMemento_fieldAccessorTable;
    }
    
    public static enum State {
      New(0, 0),
      Downloading(1, 1),
      Installing(2, 2),
      Current(3, 3),
      Old(4, 4),
      ;
      
      
      public final int getNumber() { return value; }
      
      public static State valueOf(int value) {
        switch (value) {
          case 0: return New;
          case 1: return Downloading;
          case 2: return Installing;
          case 3: return Current;
          case 4: return Old;
          default: return null;
        }
      }
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final State[] VALUES = {
        New, Downloading, Installing, Current, Old, 
      };
      public static State valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      private final int index;
      private final int value;
      private State(int index, int value) {
        this.index = index;
        this.value = value;
      }
    }
    
    // required .ProductVersionMemento version = 1;
    private boolean hasVersion;
    private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento version_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.getDefaultInstance();
    public boolean hasVersion() { return hasVersion; }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento getVersion() { return version_; }
    
    // required .ProductVersionStateMemento.State state = 2;
    private boolean hasState;
    private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.State state_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.State.New;
    public boolean hasState() { return hasState; }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.State getState() { return state_; }
    
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento();
      
      protected com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento buildPartial() {
        com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .ProductVersionMemento version = 1;
      public boolean hasVersion() {
        return result.hasVersion();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento getVersion() {
        return result.getVersion();
      }
      public Builder setVersion(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento value) {
        result.hasVersion = true;
        result.version_ = value;
        return this;
      }
      public Builder setVersion(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.Builder builderForValue) {
        result.hasVersion = true;
        result.version_ = builderForValue.build();
        return this;
      }
      public Builder mergeVersion(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento value) {
        if (result.hasVersion() &&
            result.version_ != com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.getDefaultInstance()) {
          result.version_ =
            com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.newBuilder(result.version_).mergeFrom(value).buildPartial();
        } else {
          result.version_ = value;
        }
        result.hasVersion = true;
        return this;
      }
      public Builder clearVersion() {
        result.hasVersion = false;
        result.version_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.getDefaultInstance();
        return this;
      }
      
      // required .ProductVersionStateMemento.State state = 2;
      public boolean hasState() {
        return result.hasState();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.State getState() {
        return result.getState();
      }
      public Builder setState(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.State value) {
        result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.State.New;
        return this;
      }
    }
  }
  
  public static final class ProductStateMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use ProductStateMemento.newBuilder() to construct.
    private ProductStateMemento() {}
    
    private static final ProductStateMemento defaultInstance = new ProductStateMemento();
    public static ProductStateMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProductStateMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ProductStateMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_ProductStateMemento_fieldAccessorTable;
    }
    
    // required .ProductMemento product = 1;
    private boolean hasProduct;
    private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento product_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.getDefaultInstance();
    public boolean hasProduct() { return hasProduct; }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento getProduct() { return product_; }
    
    // repeated .ProductVersionStateMemento version = 2;
    private java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento> version_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento> getVersionList() {
      return version_;
    }
    public int getVersionCount() { return version_.size(); }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento getVersion(int index) {
      return version_.get(index);
    }
    
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento();
      
      protected com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento buildPartial() {
        if (result.version_ != java.util.Collections.EMPTY_LIST) {
          result.version_ =
            java.util.Collections.unmodifiableList(result.version_);
        }
        com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // required .ProductMemento product = 1;
      public boolean hasProduct() {
        return result.hasProduct();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento getProduct() {
        return result.getProduct();
      }
      public Builder setProduct(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento value) {
        result.hasProduct = true;
        result.product_ = value;
        return this;
      }
      public Builder setProduct(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.Builder builderForValue) {
        result.hasProduct = true;
        result.product_ = builderForValue.build();
        return this;
      }
      public Builder mergeProduct(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento value) {
        if (result.hasProduct() &&
            result.product_ != com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.getDefaultInstance()) {
          result.product_ =
            com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.newBuilder(result.product_).mergeFrom(value).buildPartial();
        } else {
          result.product_ = value;
        }
        result.hasProduct = true;
        return this;
      }
      public Builder clearProduct() {
        result.hasProduct = false;
        result.product_ = com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.getDefaultInstance();
        return this;
      }
      
      // repeated .ProductVersionStateMemento version = 2;
      public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento> getVersionList() {
        return java.util.Collections.unmodifiableList(result.version_);
      }
      public int getVersionCount() {
        return result.getVersionCount();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento getVersion(int index) {
        return result.getVersion(index);
      }
      public Builder setVersion(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento value) {
        result.version_.set(index, value);
        return this;
      }
      public Builder setVersion(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.Builder builderForValue) {
        result.version_.set(index, builderForValue.build());
        return this;
      }
      public Builder addVersion(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento value) {
        if (result.version_.isEmpty()) {
          result.version_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento>();
        }
        result.version_.add(value);
        return this;
      }
      public Builder addVersion(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.Builder builderForValue) {
        if (result.version_.isEmpty()) {
          result.version_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento>();
        }
        result.version_.add(builderForValue.build());
        return this;
      }
      public Builder addAllVersion(
          java.lang.Iterable<? extends com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento> values) {
        if (result.version_.isEmpty()) {
          result.version_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento>();
        }
        super.addAll(values, result.version_);
        return this;
      }
      public Builder clearVersion() {
        result.version_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  public static final class LocalRepositoryMemento extends
      com.google.protobuf.GeneratedMessage {
    // Use LocalRepositoryMemento.newBuilder() to construct.
    private LocalRepositoryMemento() {}
    
    private static final LocalRepositoryMemento defaultInstance = new LocalRepositoryMemento();
    public static LocalRepositoryMemento getDefaultInstance() {
      return defaultInstance;
    }
    
    public LocalRepositoryMemento getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_LocalRepositoryMemento_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.yoursway.autoupdater.protos.LocalRepositoryProtos.internal_static_LocalRepositoryMemento_fieldAccessorTable;
    }
    
    // repeated .ProductStateMemento product = 1;
    private java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento> product_ =
      java.util.Collections.emptyList();
    public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento> getProductList() {
      return product_;
    }
    public int getProductCount() { return product_.size(); }
    public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento getProduct(int index) {
      return product_.get(index);
    }
    
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistry extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return new Builder(); }
    public Builder newBuilderForType() { return new Builder(); }
    public static Builder newBuilder(com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento prototype) {
      return new Builder().mergeFrom(prototype);
    }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      // Construct using com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento.newBuilder()
      private Builder() {}
      
      com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento();
      
      protected com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        result = new com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento();
        return this;
      }
      
      public Builder clone() {
        return new Builder().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento.getDescriptor();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento getDefaultInstanceForType() {
        return com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento.getDefaultInstance();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento build() {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result);
        }
        return buildPartial();
      }
      
      private com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw new com.google.protobuf.UninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento buildPartial() {
        if (result.product_ != java.util.Collections.EMPTY_LIST) {
          result.product_ =
            java.util.Collections.unmodifiableList(result.product_);
        }
        com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento returnMe = result;
        result = null;
        return returnMe;
      }
      
      
      // repeated .ProductStateMemento product = 1;
      public java.util.List<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento> getProductList() {
        return java.util.Collections.unmodifiableList(result.product_);
      }
      public int getProductCount() {
        return result.getProductCount();
      }
      public com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento getProduct(int index) {
        return result.getProduct(index);
      }
      public Builder setProduct(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento value) {
        result.product_.set(index, value);
        return this;
      }
      public Builder setProduct(int index, com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento.Builder builderForValue) {
        result.product_.set(index, builderForValue.build());
        return this;
      }
      public Builder addProduct(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento value) {
        if (result.product_.isEmpty()) {
          result.product_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento>();
        }
        result.product_.add(value);
        return this;
      }
      public Builder addProduct(com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento.Builder builderForValue) {
        if (result.product_.isEmpty()) {
          result.product_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento>();
        }
        result.product_.add(builderForValue.build());
        return this;
      }
      public Builder addAllProduct(
          java.lang.Iterable<? extends com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento> values) {
        if (result.product_.isEmpty()) {
          result.product_ = new java.util.ArrayList<com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento>();
        }
        super.addAll(values, result.product_);
        return this;
      }
      public Builder clearProduct() {
        result.product_ = java.util.Collections.emptyList();
        return this;
      }
    }
  }
  
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMemento_descriptor =
      getDescriptor().getMessageTypes().get(0);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_RequestMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_RequestMemento_descriptor,
          new java.lang.String[] { "Url", "Size", "Sha1", },
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento.class,
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.RequestMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComponentFileMemento_descriptor =
      getDescriptor().getMessageTypes().get(1);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ComponentFileMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ComponentFileMemento_descriptor,
          new java.lang.String[] { "Hash", "Size", "Modified", "Path", },
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento.class,
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentFileMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ComponentMemento_descriptor =
      getDescriptor().getMessageTypes().get(2);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ComponentMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ComponentMemento_descriptor,
          new java.lang.String[] { "File", "Pack", },
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento.class,
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ComponentMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductMemento_descriptor =
      getDescriptor().getMessageTypes().get(3);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ProductMemento_descriptor,
          new java.lang.String[] { },
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.class,
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductVersionMemento_descriptor =
      getDescriptor().getMessageTypes().get(4);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductVersionMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ProductVersionMemento_descriptor,
          new java.lang.String[] { "Product", "Pack", "Component", "Executable", },
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.class,
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductVersionStateMemento_descriptor =
      getDescriptor().getMessageTypes().get(5);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductVersionStateMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ProductVersionStateMemento_descriptor,
          new java.lang.String[] { "Version", "State", },
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.class,
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductVersionStateMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductStateMemento_descriptor =
      getDescriptor().getMessageTypes().get(6);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductStateMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_ProductStateMemento_descriptor,
          new java.lang.String[] { "Product", "Version", },
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento.class,
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.ProductStateMemento.Builder.class);
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LocalRepositoryMemento_descriptor =
      getDescriptor().getMessageTypes().get(7);
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_LocalRepositoryMemento_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessage.FieldAccessorTable(
          internal_static_LocalRepositoryMemento_descriptor,
          new java.lang.String[] { "Product", },
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento.class,
          com.yoursway.autoupdater.protos.LocalRepositoryProtos.LocalRepositoryMemento.Builder.class);
}
